### ISSUE TITLE
Download of "main" tarball fails

### ISSUE THREAD

**Issue by shawndy** [oschwengers/asap#11]
I am unable to complete the install step:
$ wget https://zenodo.org/record/3780003/files/asap.tar.gz

after about 1.5 hrs, get server error and can't re-initiate.  Happened twice, so I posted.

Is there another host?

**Comment by oschwengers** [comment]
Hi @shawndy , I just tested the hosted file. First try sucessfully finished with a stable download rate of 12 Mb/s .
Either Zenodo was temporarily down or this is somehow related to a local network issue?
May I kindly ask to give it a retry? The files are not hosted anywhere else as Zenodo is one of the most reliable hosts you can get.

**Comment by shawndy** [comment]
Thanks.  i'll try again later. It was delivering at ~1.2 Mb/s... to maybe timing out/
