### ISSUE TITLE
Rewrite Readme by usage of an popular template and adding a Makefile ✍️

### ISSUE THREAD

**Issue by TGotwig** [oschwengers/asap#13]
Hello there 🙋‍♂️

The readme doesn't explain very well how to setup for development,
and it has some other issues,
I think a rewrite along with this template would improve it a lot 👇
https://github.com/elsewhencode/project-guidelines/blob/master/README.sample.md

Also a Makefile would be nice to have an straight way to execute things (like `script` inside of package.json files) and reduce the size of the readme 🙂

**Comment by oschwengers** [comment]
Hello @TGotwig , I'm not quite sure what `some other issues` actually means, but I'm rather reluctant to rewrite the readme, but I could think of a wiki doc describing this. However, I currently do not have the time for this but I'd be happy to accept a PR for this ;-) The same holds true for the Makefile suggestions.
Best regards!
