### ISSUE TITLE
add input support

### ISSUE THREAD

**Issue by zsgit01** [oschwengers/asap#14]
This pipeline generates nice report. I have illumine single-end and pacbio sequel data. I would like to assemble using hybrid mode. Currently, the only hybrid mode supported is nanopore-pe. Can you add that support?

**Comment by oschwengers** [comment]
Hi @zsgit01 , a PacBio/Illumina hybrid assembly shouldn't be much of a problem. However, I'm not quite sure about the Illumina single-end reads. I'll check that and put it on the list for the next release.

**Comment by zsgit01** [comment]
That is great! Thank you.
