### ISSUE TITLE
Issues downloading asap.tar.gz

### ISSUE THREAD

**Issue by jdrewes2** [oschwengers/asap#23]
Hello, I am having trouble downloading the asap.tar.gz file.  I have been able to successfully download the other files on zenodo, but this larger file is not working for me. I have tried downloading it directly from zenodo just by clicking on the download button, and I have also tried the wget command in command line on my Windows 10 PC.  Do you have any suggestions? 

 I have 300 Gb of space on my hard drive available, which should be enough to download the file (which you say is 142 Gb in the manual?).  I have tried this several times over the course of the past week.

The error message I am currently getting when trying to manually click the download button on zenodo is "Failed - Server problem".  It seems to be failing at random points; I have gotten as far as 40 Gb downloaded, but usually it fails much earlier than that.  

An error message I was getting earlier in the week while trying the wget command in the windows command prompt terminal said something to the effect that too many requests were being made?  Is this an issue on my end or on zenodo's end?

Any suggestions would be much appreciated!  I am new to this and haven't had much luck when trying to Google answers.

Thanks,
Julia

**Comment by oschwengers** [comment]
Hi Julia ,
thanks for reaching out. May I ask which version of ASA³P you'd like to use? The most recent version `1.3.0` comes with a tarball which is only 24.3 Gb in size: https://zenodo.org/record/3780003

As you mentioned that you managed to download up to ~40 Gb I wonder if you maybe downloaded an older verison `1.2.2` which is much larger. If this is the case, may I kindly ask you to try the recent version?

This having said, I think this might be somehow related to either Zenodo or your connection. However, I just tested the download of the newer version linked above from Zenodo without any issues. Could you maybe try that again?

**Comment by jdrewes2** [comment]
Hi Oliver,

Thank you for your rapid response.  It looks like it did eventually download on the desktop PC late on Friday night, perhaps when there were fewer users on our work server/internet.  However, I am now having issues with the opening of that folder in WinZip.  It says that there are a variety of “invalid filenames … encountered in the archive” and after opening it I get a different error message that it is “unable to created folder….” and “unable to create directory… ”.  I suspect these may all be issues related to the work PC, so  I will try on another computer at home that isn’t as locked down perhaps.  I’ve also reached out to my IT department to see if they have any suggestions.

Sincerely,
Julia

From: Oliver Schwengers ***@***.***>
Date: Monday, November 1, 2021 at 12:40 PM
To: oschwengers/asap ***@***.***>
Cc: Julia Drewes ***@***.***>, Author ***@***.***>
Subject: Re: [oschwengers/asap] Issues downloading asap.tar.gz (Issue #23)

      External Email - Use Caution





Hi Julia ,
thanks for reaching out. May I ask which version of ASA³P you'd like to use? The most recent version 1.3.0 comes with a tarball which is only 24.3 Gb in size: https://zenodo.org/record/3780003<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fzenodo.org%2Frecord%2F3780003&data=04%7C01%7Cjdrewes2%40jhmi.edu%7Cc986b8a5f3f24d47509908d99d565dd6%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637713816541777584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SOv78iYPKYkGlyyDe3cn6IWY4XbIPhE%2FK2Vv%2BeTDDmM%3D&reserved=0>

As you mentioned that you managed to download up to ~40 Gb I wonder if you maybe downloaded an older verison 1.2.2 which is much larger. If this is the case, may I kindly ask you to try the recent version?

This having said, I think this might be somehow related to either Zenodo or your connection. However, I just tested the download of the newer version linked above from Zenodo without any issues. Could you maybe try that again?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foschwengers%2Fasap%2Fissues%2F23%23issuecomment-956393641&data=04%7C01%7Cjdrewes2%40jhmi.edu%7Cc986b8a5f3f24d47509908d99d565dd6%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637713816541787578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VV%2FZxj0tpnw%2Bq6a2PdliMvJ%2FoGSd6jSnG5L7vEeDwfg%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOTI6UTM2KE73DMBRKAMBA3UJ27JFANCNFSM5G74YCFA&data=04%7C01%7Cjdrewes2%40jhmi.edu%7Cc986b8a5f3f24d47509908d99d565dd6%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637713816541787578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=539oTji89dWCgMXPLFr7bWXLabDwgJC%2FJQy%2BvYLXVek%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjdrewes2%40jhmi.edu%7Cc986b8a5f3f24d47509908d99d565dd6%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637713816541797574%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GZryPnuJDeAdOEgggoFW%2BDJwxv0fEneclQIko8AIF30%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjdrewes2%40jhmi.edu%7Cc986b8a5f3f24d47509908d99d565dd6%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637713816541807572%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uCUC3dOTZX3K4u2SPMYh22R%2FvAsCPabxZn3%2BjTkRL88%3D&reserved=0>.

**Comment by oschwengers** [comment]
Hi Julia,
OK then it seems to be rather related to your local network. I'll nevertheless keep this open for a while.

As you mentioned Winzip, ASA³P was neither developed for nor tested on Windows. So just in case you try using ASA³P on Windows we cannot provide any support or guidance. We've tested it on Linux and MacOS.

**Comment by oschwengers** [comment]
Hi Julia,
may I ask how it is going? Any progress? Since this is open for a quite while, I'm going to close this for now. Please, do not hesitate to re-open it just in case the issue remains or you have any further questions.
Best regards!
