### ISSUE TITLE
Bioconda package?

### ISSUE THREAD

**Issue by tseemann** [oschwengers/asap#3]
Do you think there will ever be a bioconda package for `asap`?

**Comment by oschwengers** [comment]
I wish I could say yes, but there are just too many 3rd party executables which are not accessible via Bioconda (at least this was true when we started to develop ASA³P). And additionally, there is also a mixture of Python2/3, Perl dependencies. As we're currently in a review process and I'm trying to get 2 other projects published I have no time to take a deeper look right now. But I'll have a look at this again. Until then, Docker or maybe Singularity will be our package work horses. Or, if it is an option for you, our OpenStack cloud version.
If you give it a try, please let me know what you think!
