### ISSUE TITLE
Error: wrong characters in strain (1)!

### ISSUE THREAD

**Issue by marade** [oschwengers/asap#4]
I used the -c option to check my configuration input and received this cryptic error. How does one debug this?

**Comment by oschwengers** [comment]
Thanks @marade for pointing at this and filing this issue.
It means that the strain designation within the config file contains invalid characters. Only alpha-numerics, '-' and '.' are allowed with min and max length of 2 and 50, respectively.

The `-c/--check` option is a feature from the early development stage. I guess no one has used it so far...
But indeed, this needs a solid review and leaves space for much improvement! 

As I am writing this, I'm improving the checks and rewriting the error messages. I'll test and upload a  patch version as soon as possible. I'll let you know.

**Comment by oschwengers** [comment]
@marade , I just released a patch version v1.2.2 enhancing the check logic via `-c/--check` and improving the error messages.

This comes with an updated [asap.tar.gz](https://s3.computational.bio.uni-giessen.de/swift/v1/asap/v1.2.2/asap.tar.gz).

Sorry for the inconvenience, this was heavily overdue.
I hope this helps. Please let me know, if there is more to improve - just reopen this issue or file another one.

**Comment by marade** [comment]
Thanks for the rapid response @oschwengers. I appreciate your help.
