### ISSUE TITLE
asap/asap-docker.sh script can not be found in its container

### ISSUE THREAD

**Issue by meizhao12** [oschwengers/asap#8]
Hi, I requested our school computing center to install ASAP. However, they failed to install it. Below is what they reported.

Following instructions given at

https://github.com/oschwengers/asap#docker

I was trying to build ASA3P singularity container (asa3p.simg) from its docker image hosted at

https://hub.docker.com/r/oschwengers/asap/

The following is the command I used:

singularity build asa3p.simg docker://oschwengers/asap

asa3p.simg was generated. However, ASA3P core scripts were not generated successfully in asa3p.simg. Its asap/asap-docker.sh script can not be found in its container.

**Comment by oschwengers** [comment]
Hi @meizhao12 and thanks for reaching out. So far I do not have any experience with an ASA³P singularity image derived from the Docker image. I haven't tested it yet but I guess there might be some issues as ASA³P is using a Singularity container itself in its Docker container. But feel free to play around and feed back your findings.

Regarding the `asap-docker.sh` script: This is not included within the Docker image. It is included in the asap volume (`asap.tar.gz`). Just download and extract the tarball and then execute the shell script. It will itself start the Docker container.

Please, let me know if I I could clarify your issues a little bit. If not, please do not hesitate to keep asking.

**Comment by oschwengers** [comment]
I'll close this issue. If the issue remains or there are unanswered questions, please feel free to reopen this.
