### ISSUE TITLE
Question: how to specify threads in asap-docker.sh?

### ISSUE THREAD

**Issue by telatin** [oschwengers/asap#9]
When running `asap-docker.sh` is there a way to set the max number of threads?

**Comment by oschwengers** [comment]
Hi @telatin ,
unfortunately, right now the answer is no. So far no one has asked for this. But it should not be much of a deal to implement this. I'll put it on the list for the next release.

**Comment by telatin** [comment]
Thanks, that would be highly appreciated.
Out of curiosity is it currently set to use 8 cores or so?

**Comment by oschwengers** [comment]
Yes, ASA³P is currently working with bins of 8 core per genome. In the early beginnings we saw that for many tools 8 cores per process / genome is sort of a sweatspot. Of course, there a variations and plenty of outliers, but in general we deemed it a reasonable default. Hence, in principle, ASA³P analyses 1 genome per 8 cores.
